#!/usr/bin/env bash
# Spin up an Inferentia compile box, compile useful-cub-58-st at the
# requested shape, SCP the .pt artifact back to /tei-models/, and terminate.
# Uses aws-cli directly — no Pulumi (this is a one-shot, no need for
# state-tracked infra).
#
# Usage:  ./compile.sh                         # inf2 bs=8 sl=256 bf16 (defaults)
#         TARGET=inf1 ./compile.sh             # compile for Inferentia1
#         BS=4 SL=256 TARGET=inf1 ./compile.sh # override shape + chip
#
# Env vars (all optional):
#   TARGET=inf1|inf2     which chip generation to target. Default: inf2.
#   BS=N                 trace batch size. Default: 8.
#   SL=N                 trace sequence length. Default: 256.
#   AUTO_CAST=bf16|fp16  numeric cast. inf1 supports fp16 only.
#
# Reads /workspace/.env for AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY.
# Reuses the bench-key keypair generated by bench.sh.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

RUN_T0=$(date +%s)
log()  { printf '[%s | +%4ds | compile] %s\n' \
           "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(( $(date +%s) - RUN_T0 ))" "$*" >&2; }
warn() { log "WARN: $*"; }
die()  { log "FATAL: $*"; exit 1; }

# --- env ---
log "loading env from /workspace/.env"
if [ -f /workspace/.env ]; then
  set -a; source /workspace/.env; set +a
fi
: "${AWS_ACCESS_KEY_ID:?missing AWS_ACCESS_KEY_ID}"
: "${AWS_SECRET_ACCESS_KEY:?missing AWS_SECRET_ACCESS_KEY}"
: "${AWS_REGION:=eu-central-1}"
# aws-cli reads AWS_DEFAULT_REGION, not AWS_REGION. Export both so any
# library Pick reads whichever it expects.
export AWS_REGION AWS_DEFAULT_REGION="$AWS_REGION"
log "aws region: $AWS_REGION"

# --- compile parameters (override via env) ---
TARGET="${TARGET:-inf2}"
BS="${BS:-8}"
SL="${SL:-256}"
AUTO_CAST="${AUTO_CAST:-bf16}"
SOURCE_MODEL_DIR="${SOURCE_MODEL_DIR:-/tei-models/useful-cub-58-st}"
case "$TARGET" in
  inf1)
    # Compile on inf1.6xlarge (24 vCPU, 48 GB RAM). Smaller instances OOM
    # for XLM-R base — inf1.xlarge (8 GB) died mid-trace, inf1.2xlarge
    # (16 GB) died right after "Compiler PASS" during the post-trace
    # integration step. neuron-cc + torch-neuron's combined peak memory
    # for a 278M-param transformer regularly hits 20+ GB. The compiled
    # .pt itself runs fine on inf1.xlarge at serve time; this is a
    # compile-time toolchain constraint, not a runtime one.
    INSTANCE_TYPE="inf1.6xlarge"
    NEURON_VERSION=1
    # On Inferentia1 the venv is /opt/aws_neuron_venv_pytorch_* (no 'x')
    REMOTE_VENV_GLOB='/opt/aws_neuron_venv_pytorch_*'
    # inf1 only supports fp16 — silently downgrade bf16 here too so the
    # artifact filename reflects what actually happened.
    [ "$AUTO_CAST" = "bf16" ] && AUTO_CAST="fp16" && \
      log "TARGET=inf1: downgrading auto-cast bf16 -> fp16 (chip support)"
    ;;
  inf2)
    INSTANCE_TYPE="inf2.xlarge"
    NEURON_VERSION=2
    REMOTE_VENV_GLOB='/opt/aws_neuronx_venv_pytorch_*'
    ;;
  *)
    die "unknown TARGET=$TARGET (want inf1 or inf2)"
    ;;
esac
ARTIFACT_BASE="useful-cub-58-st.neuron-${TARGET}-bs${BS}-sl${SL}"
ARTIFACT_LOCAL="/tei-models/${ARTIFACT_BASE}.pt"
log "compile config: target=$TARGET instance=$INSTANCE_TYPE bs=$BS sl=$SL auto-cast=$AUTO_CAST"
log "source:         $SOURCE_MODEL_DIR"
log "artifact:       $ARTIFACT_LOCAL"

[ -d "$SOURCE_MODEL_DIR" ] || die "source model dir $SOURCE_MODEL_DIR not found"
[ -f "$SOURCE_MODEL_DIR/model.safetensors" ] || die "no model.safetensors in source dir"

# --- keypair (reuse bench-key generated by bench.sh) ---
KEY_FILE="${HERE}/bench-key"
KEY_NAME="bench-compile-key"
[ -f "$KEY_FILE" ] || die "bench-key not found at $KEY_FILE; run ./bench.sh once first to generate"
SSH_OPTS=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          -o ConnectTimeout=10 -o LogLevel=ERROR -i "$KEY_FILE")

# --- AMI lookup ---
# Inf1 and Inf2 use different DLAMIs — the multi-framework DLAMI (ubuntu-24.04)
# only ships the torch_neuronx (inf2) venv. Inf1 SDK is frozen at PyTorch 1.13
# so AWS ships a dedicated inf1 AMI tagged `pt_1_13_inf1_ami_u22`.
if [ "$TARGET" = "inf1" ]; then
  DLAMI_NEURON_SSM="/aws/service/neuron/dlami/pt_1_13_inf1_ami_u22/ubuntu-22.04/latest/image_id"
else
  DLAMI_NEURON_SSM="/aws/service/neuron/dlami/multi-framework/ubuntu-24.04/latest/image_id"
fi
log "looking up Neuron DLAMI AMI ($DLAMI_NEURON_SSM)"
AMI=$(aws ssm get-parameter --name "$DLAMI_NEURON_SSM" \
        --query 'Parameter.Value' --output text)
log "AMI: $AMI"

# --- VPC + subnet ---
log "looking up default VPC + subnet"
VPC=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=true \
        --query 'Vpcs[0].VpcId' --output text)
SUBNET=$(aws ec2 describe-subnets --filters Name=vpc-id,Values=$VPC \
        --query 'Subnets[0].SubnetId' --output text)
log "VPC=$VPC  SUBNET=$SUBNET"

# --- keypair ensure ---
log "ensuring keypair $KEY_NAME"
if ! aws ec2 describe-key-pairs --key-names "$KEY_NAME" --output text >/dev/null 2>&1; then
  aws ec2 import-key-pair --key-name "$KEY_NAME" \
    --public-key-material "fileb://${KEY_FILE}.pub" >/dev/null
  log "  imported"
else
  log "  exists"
fi

# --- security group ensure ---
log "ensuring security group bench-compile-sg"
SG=$(aws ec2 describe-security-groups \
       --filters "Name=group-name,Values=bench-compile-sg" "Name=vpc-id,Values=$VPC" \
       --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)
if [ -z "$SG" ] || [ "$SG" = "None" ]; then
  SG=$(aws ec2 create-security-group --group-name bench-compile-sg \
         --description "aws-embedding-bench compile box: ssh only" \
         --vpc-id "$VPC" --query 'GroupId' --output text)
  aws ec2 authorize-security-group-ingress --group-id "$SG" \
    --protocol tcp --port 22 --cidr 0.0.0.0/0 >/dev/null
  log "  created $SG"
else
  log "  reusing $SG"
fi

# --- launch ---
# Substitute the venv glob into compile_userdata.sh so the same script handles
# inf1 (aws_neuron_venv) and inf2 (aws_neuronx_venv).
USERDATA_RENDERED=$(mktemp)
sed "s|__NEURON_VENV_GLOB__|$REMOTE_VENV_GLOB|g" \
    "${HERE}/compile_userdata.sh" > "$USERDATA_RENDERED"

log "launching $INSTANCE_TYPE (target=$TARGET, venv-glob=$REMOTE_VENV_GLOB)"
INSTANCE_ID=$(aws ec2 run-instances \
  --instance-type "$INSTANCE_TYPE" \
  --image-id "$AMI" \
  --subnet-id "$SUBNET" \
  --security-group-ids "$SG" \
  --key-name "$KEY_NAME" \
  --user-data "file://$USERDATA_RENDERED" \
  --block-device-mappings 'DeviceName=/dev/sda1,Ebs={VolumeSize=120,VolumeType=gp3,DeleteOnTermination=true}' \
  --tag-specifications "ResourceType=instance,Tags=[{Key=Project,Value=aws-embedding-bench-compile},{Key=Name,Value=compile-$TARGET}]" \
  --associate-public-ip-address \
  --query 'Instances[0].InstanceId' --output text)
rm -f "$USERDATA_RENDERED"
log "instance: $INSTANCE_ID"

# --- trap: always terminate (incl. on failure) ---
trap '
  log "trap fired — terminating '"$INSTANCE_ID"'"
  aws ec2 terminate-instances --instance-ids "'"$INSTANCE_ID"'" --output text >/dev/null 2>&1 || true
' EXIT
trap '
  log "INT/TERM caught — terminating '"$INSTANCE_ID"' and exiting"
  aws ec2 terminate-instances --instance-ids "'"$INSTANCE_ID"'" --output text >/dev/null 2>&1 || true
  exit 130
' INT TERM

log "waiting for instance state=running"
aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
PUBLIC_IP=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" \
              --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
log "public IP: $PUBLIC_IP"

# --- wait for SSH ---
log "waiting for SSH (polls every 5s, timeout 5min)"
ssh_t0=$(date +%s)
for attempt in $(seq 1 60); do
  if ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "true" 2>/dev/null; then
    log "SSH ready after $attempt probe(s) ($(( $(date +%s) - ssh_t0 ))s)"
    break
  fi
  sleep 5
done
ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "true" 2>/dev/null || die "SSH never came up"

# --- wait for compile-deps-ready sentinel ---
log "waiting for /var/run/compile-deps-ready (deps verify ~3-5min)"
deps_t0=$(date +%s)
for attempt in $(seq 1 60); do
  if ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "test -f /var/run/compile-deps-ready" 2>/dev/null; then
    CONTENT=$(ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "cat /var/run/compile-deps-ready" 2>/dev/null || echo "")
    log "deps-ready after $attempt probe(s) ($(( $(date +%s) - deps_t0 ))s): $CONTENT"
    if [[ "$CONTENT" == fatal:* ]]; then
      ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "sudo tail -50 /var/log/compile-userdata.log" >&2 || true
      die "deps install failed"
    fi
    break
  fi
  [ $((attempt % 6)) -eq 0 ] && \
    log "  ... still installing (attempt $attempt, $(( $(date +%s) - deps_t0 ))s)"
  sleep 10
done

# --- SCP source model + compile script ---
log "SCPing source model from $SOURCE_MODEL_DIR (~1.1 GB)"
# Use -r to recurse the SentenceTransformers subdirs (1_Pooling, 2_Dense, 3_Normalize).
# Use bash glob to skip the .pt/.neff files in the parent directory.
scp -r "${SSH_OPTS[@]}" "$SOURCE_MODEL_DIR"/. "ubuntu@$PUBLIC_IP:/opt/source-model/"
log "SCPing compile_neuron.py to /home/ubuntu/"
scp "${SSH_OPTS[@]}" "${HERE}/compile_neuron.py" "ubuntu@$PUBLIC_IP:/home/ubuntu/compile_neuron.py"

# --- run compile ---
# Resolve the actual venv path on the remote (the glob may match multiple
# versions; pick the most recent). Saves us hardcoding 2_9 etc.
VENV=$(ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" \
       "ls -d $REMOTE_VENV_GLOB/ 2>/dev/null | grep -Ev 'nxd_(training|inference)/?$' | sort -V | tail -1 | sed 's:/\$::'" \
       2>/dev/null)
[ -n "$VENV" ] || die "no venv matched $REMOTE_VENV_GLOB on remote"
log "remote venv: $VENV"
log "running compile_neuron.py on remote (bs=$BS sl=$SL auto-cast=$AUTO_CAST neuron-v=$NEURON_VERSION)"
# Remote bash gets its own `set -o pipefail` so python's non-zero exit
# propagates through `tee`; without it, tee always returns 0 and we'd
# silently treat a failed compile as success. Save the log to /home/ubuntu/
# (persists across SSH sessions) so a follow-up SSH can dump it on failure.
set +e
ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" \
  "bash -c 'set -o pipefail; PATH=$VENV/bin:\$PATH \
     $VENV/bin/python /home/ubuntu/compile_neuron.py \
       --source /opt/source-model \
       --output /home/ubuntu/${ARTIFACT_BASE}.pt \
       --batch-size $BS \
       --seq-len $SL \
       --auto-cast $AUTO_CAST \
       --neuron-version $NEURON_VERSION 2>&1 | tee /home/ubuntu/compile.log'" \
  | while IFS= read -r line; do log "[remote] $line"; done
RC=$?
set -e
if [ $RC -ne 0 ]; then
  log "remote compile exited $RC; full remote log (tail -200):"
  ssh "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP" "tail -200 /home/ubuntu/compile.log" \
    2>&1 | sed 's/^/    /' >&2 || true
  die "compile failed (see remote tail above)"
fi

# --- SCP artifact back ---
log "SCPing artifact back to $ARTIFACT_LOCAL"
scp "${SSH_OPTS[@]}" "ubuntu@$PUBLIC_IP:/home/ubuntu/${ARTIFACT_BASE}.pt" "$ARTIFACT_LOCAL"
ARTIFACT_SIZE=$(du -h "$ARTIFACT_LOCAL" 2>/dev/null | cut -f1)
log "artifact: $ARTIFACT_LOCAL ($ARTIFACT_SIZE)"

log "compile complete; total wall-clock: $(( $(date +%s) - RUN_T0 ))s"
log "instance $INSTANCE_ID will be terminated by exit trap"
