"""The load-bearing gate for `ce-service`: the query/article splice.

A wrong splice produces PLAUSIBLE SCORES, not an error. Nothing downstream can
catch it — not the model, not the query service, not a healthcheck. So the
splice is frozen against a committed fixture (`ceserve/golden/splice_fixture.json`,
generated by `pipeline/gen_ce_splice_fixture.py`) and checked here, in CI without
a GPU or a 470 MB checkpoint, and again at boot on the serving box
(`scorer.assert_golden_fixture`).

Three layers:

  1. `assemble()` reproduces the pinned ids/mask exactly.
  2. Those ids equal HF's own pair encoding — the same reference
     `bench_ce_t4.parity_gate` compares against, frozen here.
  3. `decode_token_ids()` round-trips the ES `binary` wire form, including
     against the ids the JVM indexer committed in /next-gen's own fixture.
     That third one is what catches a byte-order mistake.

MXG-144.
"""
import base64
import json
import sys
from pathlib import Path

import numpy as np
import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "ce-service"))

from ceserve import SPLICE_FIXTURE  # noqa: E402
from ceserve.constants import BOS, EOS, HEAD_EXTRA, PAD, VOCAB_SIZE  # noqa: E402
from ceserve.fold_de import fold_de  # noqa: E402
from ceserve.splice import (  # noqa: E402
    TokenDecodeError,
    assemble,
    clamp_max_len,
    decode_token_ids,
    encode_query,
)

# /next-gen's own cross-language fixture, written by the SAME tokenizer.json and
# read by CeTokenizerTest. Optional: the repo is not always checked out beside
# this one, and skipping is better than pinning a copy that can drift.
NEXTGEN_TOKEN_FIXTURES = Path(
    "/next-gen/article/search/commons/src/test/resources/ce/token-fixtures.json"
)


@pytest.fixture(scope="module")
def fixture():
    return json.loads(SPLICE_FIXTURE.read_text())


def pytest_generate_tests(metafunc):
    if "case" in metafunc.fixturenames:
        payload = json.loads(SPLICE_FIXTURE.read_text())
        metafunc.parametrize(
            "case", payload["cases"], ids=[c["name"] for c in payload["cases"]]
        )


# --------------------------------------------------------------- constants --

def test_fixture_pins_the_tokenizer_and_specials(fixture):
    """The fixture is only meaningful for the vocabulary it was built from.

    A tokenizer swapped underneath a version string is the one failure mode no
    downstream check would catch (CeProperties' KDoc says the same), so the
    digest travels with the ids.
    """
    assert fixture["tokenizerSha256"] == (
        "3a56def25aa40facc030ea8b0b87f3688e4b3c39eb8b45d5702b3a1300fe2a20"
    )
    assert (fixture["bos"], fixture["eos"], fixture["pad"]) == (BOS, EOS, PAD)
    assert fixture["headExtra"] == HEAD_EXTRA
    assert fixture["indexArticleCap"] == 508, (
        "the indexer runs CE_MAX_LEN=512 deliberately; 512 - HEAD_EXTRA = 508"
    )


# ------------------------------------------------------------ layer 1: pins --

def test_assemble_matches_the_frozen_splice(case):
    q_ids = np.asarray(case["queryIds"], dtype=np.int64)
    arts = [decode_token_ids(a["tokensB64"], a["tokenCount"])
            for a in case["articles"]]
    ids, mask, max_seq = assemble(q_ids, arts, case["maxLen"], None)

    assert ids.tolist() == case["expectedIds"], case["note"]
    assert mask.tolist() == case["expectedMask"], case["note"]
    assert max_seq == case["expectedMaxSeq"]


# ------------------------------------------------- layer 2: the HF reference --

def test_spliced_ids_equal_hf_pair_encoding(case):
    """`ids[i][mask[i] == 1]` must be byte-for-byte HF's `tok(q, a, truncation=True)`.

    This is `bench_ce_t4.parity_gate`, frozen. That gate ran 3,000 pairs live and
    found 3,000/3,000 identical; the fixture carries a representative slice so CI
    can assert it with no model present.
    """
    if not case["hfParity"]:
        pytest.skip(case["note"])
    ids = np.asarray(case["expectedIds"], dtype=np.int64)
    mask = np.asarray(case["expectedMask"], dtype=np.int64)
    assert len(case["hfReference"]) == len(case["articles"])
    for i, want in enumerate(case["hfReference"]):
        got = ids[i][mask[i] == 1].tolist()
        assert got == want, (
            f"row {i} of {case['name']}: spliced ids differ from HF's pair "
            f"encoding (len {len(got)} vs {len(want)})"
        )


def test_only_second_truncation_trims_the_article_not_the_query(case):
    """The query survives intact whenever it fits; only the article is trimmed."""
    if not case["hfParity"]:
        pytest.skip(case["note"])
    ids = np.asarray(case["expectedIds"], dtype=np.int64)
    nq = len(case["queryIds"])
    for row in ids:
        assert row[1:nq + 1].tolist() == case["queryIds"]


# ------------------------------------------------ layer 3: structural truths --

def test_structural_invariants(case):
    ids = np.asarray(case["expectedIds"], dtype=np.int64)
    mask = np.asarray(case["expectedMask"], dtype=np.int64)
    seq = mask.sum(1)
    # `assemble` clamps a pathologically long query, so nq is what SURVIVED the
    # clamp, not what was handed in.
    nq = int(min(len(case["queryIds"]),
                 max(1, case["maxLen"] - HEAD_EXTRA - 1)))

    assert (ids[:, 0] == BOS).all(), "every row opens with <s>"
    assert (ids[:, nq + 1] == EOS).all() and (ids[:, nq + 2] == EOS).all(), (
        "the pair separator is </s></s>, not a single </s>"
    )
    for i, n in enumerate(seq):
        assert ids[i, n - 1] == EOS, "every row closes with </s>"
        assert not (ids[i, :n] == PAD).any(), (
            "no PAD may sit under an attended position — that is the trap "
            "`_reset_backend` exists for, and it is silent"
        )
        assert (ids[i, n:] == PAD).all(), "everything past seq is PAD"
    assert ids.shape[1] == int(seq.max()), "pad-to-longest, not fixed width"
    assert int(seq.max()) <= case["maxLen"], (
        "no row may exceed max_len — the model would index past its position "
        "embeddings"
    )
    assert (ids >= 0).all() and (ids < VOCAB_SIZE).all()


def test_article_lengths_follow_the_budget(case):
    """`budget = maxLen - nq - HEAD_EXTRA`, and the article is trimmed to it."""
    mask = np.asarray(case["expectedMask"], dtype=np.int64)
    nq = int(min(len(case["queryIds"]),
                 max(1, case["maxLen"] - HEAD_EXTRA - 1)))
    budget = max(1, case["maxLen"] - nq - HEAD_EXTRA)
    for i, art in enumerate(case["articles"]):
        want = min(art["tokenCount"], budget)
        assert int(mask[i].sum()) == want + nq + HEAD_EXTRA


# ------------------------------------------------- the wire format (decode) --

def test_decode_round_trips_the_fixture(case):
    for art in case["articles"]:
        ids = decode_token_ids(art["tokensB64"], art["tokenCount"])
        assert ids.dtype == np.int64
        assert ids.shape[0] == art["tokenCount"]
        # Re-pack and compare bytes: this is the direction a byte-order mistake
        # would survive a value comparison.
        repacked = base64.b64encode(
            ids.astype("<i4").tobytes()).decode("ascii")
        assert repacked == art["tokensB64"]


def test_decode_is_little_endian_not_native():
    """Explicit, because both orders decode to *valid* ids on a little-endian
    host and only differ on a big-endian one — where the bug would be silent."""
    ids = [7, 250001, 0, 128]
    blob = base64.b64encode(np.asarray(ids, dtype="<i4").tobytes()).decode()
    assert decode_token_ids(blob, len(ids)).tolist() == ids

    swapped = base64.b64encode(np.asarray(ids, dtype=">i4").tobytes()).decode()
    try:
        got = decode_token_ids(swapped, len(ids)).tolist()
    except TokenDecodeError:
        # The vocabulary bound catches most swaps, which is the good outcome.
        return
    assert got != ids, "a native-order read must not silently reproduce the ids"


@pytest.mark.parametrize(
    "blob,count,message",
    [
        (None, None, "missing"),
        (b"", None, "missing"),
        ("!!!!not base64!!!!", None, "base64"),
        (base64.b64encode(b"\x01\x02\x03").decode(), None, "multiple of 4"),
        (base64.b64encode(np.asarray([1, 2], dtype="<i4").tobytes()).decode(),
         3, "ceTokenCount"),
        (base64.b64encode(np.asarray([1, 999_999], dtype="<i4").tobytes()).decode(),
         2, "outside vocabulary"),
        (base64.b64encode(np.asarray([1, -5], dtype="<i4").tobytes()).decode(),
         2, "outside vocabulary"),
    ],
)
def test_decode_rejects_corrupt_blobs(blob, count, message):
    with pytest.raises(TokenDecodeError) as exc:
        decode_token_ids(blob, count)
    assert message in str(exc.value)


def test_empty_blob_is_a_valid_zero_length_article():
    """An article with no tokens is a real, expected shape — `CeTokenEnricher`
    leaves the fields UNSET for offer-less articles, but a genuinely empty
    rendering packs to zero bytes and must not be confused with corruption."""
    assert decode_token_ids(base64.b64encode(b"").decode(), 0).tolist() == []


@pytest.mark.skipif(
    not NEXTGEN_TOKEN_FIXTURES.exists(),
    reason="/next-gen not checked out beside this repo",
)
def test_decodes_the_ids_the_jvm_indexer_committed():
    """Cross-language gate, for free.

    `token-fixtures.json` is written by `pipeline/gen_ce_token_fixtures.py` from
    the same `tokenizer.json` and read by `CeTokenizerTest`, which asserts the
    JVM produces those ids and packs them little-endian int32. Packing them here
    and decoding through the service's own decoder closes the loop
    `CeTokenizer.encodePacked -> ES binary -> ce-service` without either side
    trusting a description of the other.
    """
    payload = json.loads(NEXTGEN_TOKEN_FIXTURES.read_text())
    assert payload["tokenizerSha256"] == (
        "3a56def25aa40facc030ea8b0b87f3688e4b3c39eb8b45d5702b3a1300fe2a20"
    ), "the two gates must be built from the same vocabulary or neither means anything"
    checked = 0
    for entry in payload["fixtures"]:
        ids = entry["cappedIds"]
        blob = base64.b64encode(
            np.asarray(ids, dtype="<i4").tobytes()).decode("ascii")
        assert decode_token_ids(blob, len(ids)).tolist() == ids
        checked += 1
    for entry in payload.get("articleFixtures", []):
        ids = entry["expectedCappedIds"]
        blob = base64.b64encode(
            np.asarray(ids, dtype="<i4").tobytes()).decode("ascii")
        assert decode_token_ids(blob, len(ids)).tolist() == ids
        checked += 1
    assert checked > 0


# --------------------------------------------------------- property sweeps --

@pytest.mark.parametrize("seed", range(12))
def test_random_shapes_hold_every_invariant(seed):
    """The fixture covers the shapes somebody thought of. This covers the rest."""
    rng = np.random.default_rng(seed)
    max_len = int(rng.integers(8, 257))
    nq_in = int(rng.integers(1, 300))
    k = int(rng.integers(1, 40))
    q_ids = rng.integers(4, VOCAB_SIZE, size=nq_in, dtype=np.int64)
    arts = [rng.integers(4, VOCAB_SIZE, size=int(rng.integers(0, 600)),
                         dtype=np.int64) for _ in range(k)]

    ids, mask, max_seq = assemble(q_ids, arts, max_len, None)
    nq = min(nq_in, max(1, max_len - HEAD_EXTRA - 1))
    budget = max(1, max_len - nq - HEAD_EXTRA)
    seq = mask.sum(1)

    assert ids.shape == (k, max_seq) == mask.shape
    assert max_seq <= max_len
    assert (ids[:, 0] == BOS).all()
    assert (ids[:, nq + 1] == EOS).all() and (ids[:, nq + 2] == EOS).all()
    for i, art in enumerate(arts):
        n = int(seq[i])
        assert n == min(art.shape[0], budget) + nq + HEAD_EXTRA
        assert ids[i, n - 1] == EOS
        assert not (ids[i, :n] == PAD).any()
        assert (ids[i, n:] == PAD).all()
        kept = min(art.shape[0], budget)
        assert ids[i, nq + 3:nq + 3 + kept].tolist() == art[:kept].tolist()


def test_pad_to_fixed_width_still_bounded_by_max_len():
    """`pad_to` is not used at serve time (pad-to-longest is worth 1.9-2.0x),
    but the bench sweeps it and the two paths must not diverge."""
    q = np.arange(4, 9, dtype=np.int64)
    arts = [np.arange(10, 40, dtype=np.int64)]
    ids, mask, _ = assemble(q, arts, 192, 64)
    assert ids.shape[1] == 64
    ids, mask, _ = assemble(q, arts, 32, 64)
    assert ids.shape[1] == 64 and int(mask.sum(1).max()) <= 32, (
        "pad_to widens the tensor but max_len still bounds the content"
    )


# --------------------------------------- query contract (MXG-177) / max_len --

def test_fold_de_matches_the_training_contract():
    """The exact table `pipeline/fold_de.py` self-checks, plus the row
    `pipeline/tests/test_train_ce_query_contract.py` pins: whitespace is
    PRESERVED (fold_de alone, no normalize_text collapse — that composition is
    the SPLADE chain, and copying it here would be a silent contract break)."""
    table = {
        "Kühlschrank": "kuehlschrank",
        "Schloßschraube GROß": "schlossschraube gross",
        "für": "fuer",
        "Größe": "groesse",
        "V4034PX": "v4034px",
        "Café": "cafe",
        "Messlöffel  M8X40": "messloeffel  m8x40",
        "": "",
    }
    for src, want in table.items():
        assert fold_de(src) == want, src


def test_fold_de_is_idempotent():
    for src in ("Kühlschrank", "Schloßschraube GROß", "Café", "bosch  gsr 12v"):
        once = fold_de(src)
        assert fold_de(once) == once, src


def test_encode_query_applies_no_prefix():
    """Under the retired contract encode_query prepended '[segment] '. Now it
    encodes the caller's (already folded) text verbatim."""

    class Recorder:
        def __init__(self):
            self.seen = []

        def encode(self, text, add_special_tokens=False):
            self.seen.append((text, add_special_tokens))

            class Enc:
                ids = [1, 2, 3]

            return Enc()

    tok = Recorder()
    ids = encode_query(tok, "kuehlschrank  gross")
    assert tok.seen == [("kuehlschrank  gross", False)]
    assert ids.tolist() == [1, 2, 3] and ids.dtype == np.int64


@pytest.mark.parametrize("requested,expected", [(None, 192), (128, 128), (192, 192), (8, 8)])
def test_max_len_dial(requested, expected):
    assert clamp_max_len(requested, 192) == expected


@pytest.mark.parametrize("bad", [7, 0, -1, 193, 512])
def test_max_len_outside_the_dial_is_refused(bad):
    with pytest.raises(ValueError):
        clamp_max_len(bad, 192)
