"""Article-level embedding text rendering for the bulk indexer.

Delegates to the production training-time renderer
(`embedding_train.rendering.RowTextRenderer`) so that a TEI cache miss
in `indexer.tei_cache` produces a vector in the same distribution as
the embeddings cached by `scripts/prewarm_tei_cache.py` (which were
generated by the same renderer when `offers_embedded_full.parquet` was
built). Reusing one renderer rather than reimplementing the template is
a load-bearing correctness property — silent drift between the two
paths would mix two distributions in one Milvus collection.

The template, preprocessing rules (`clean_html`, `flatten_category_paths`,
text normalization), and field-set live in `configs/data/default.yaml`
and `embedding_train/text.py`. Bumping any of those breaks every cached
embedding — pair the change with a `HASH_VERSION` bump
(`indexer/projection.py`) so the cache key prefix shifts and Redis
returns clean misses.
"""

from __future__ import annotations

from pathlib import Path
from threading import Lock
from typing import Any

import yaml

from embedding_train.rendering import RowTextRenderer


_DEFAULT_YAML = (
    Path(__file__).resolve().parent.parent / "configs/data/default.yaml"
)

# Parquet bucket files (`offers_grouped.parquet`, `offers_embedded_full.parquet`)
# carry camelCase column names; the production template expects
# snake_case. Mirrors the example block in `configs/data/default.yaml`
# (the YAML's own `column_rename: null` is a default — overridden here
# at indexer load time).
_PARQUET_COLUMN_RENAME = {
    "manufacturerName": "manufacturer_name",
    "categoryPaths": "category_paths",
    "manufacturerArticleNumber": "manufacturer_article_number",
    "manufacturerArticleType": "manufacturer_article_type",
}


class _CfgWrapper:
    """Minimal attribute + .get adapter so RowTextRenderer accepts a
    plain dict instead of OmegaConf. RowTextRenderer reads
    `query_template`, `offer_template`, `clean_html`, `positive_label`
    via attribute, and `column_rename` / `column_mapping` via .get."""

    def __init__(self, d: dict[str, Any]) -> None:
        self._d = d

    def __getattr__(self, name: str) -> Any:
        if name in self._d:
            return self._d[name]
        raise AttributeError(name)

    def get(self, key: str, default: Any = None) -> Any:
        return self._d.get(key, default)


_renderer: RowTextRenderer | None = None
_renderer_lock = Lock()


def _get_renderer() -> RowTextRenderer:
    global _renderer
    if _renderer is None:
        with _renderer_lock:
            if _renderer is None:
                with open(_DEFAULT_YAML) as f:
                    cfg = yaml.safe_load(f)
                cfg["column_rename"] = _PARQUET_COLUMN_RENAME
                _renderer = RowTextRenderer(_CfgWrapper(cfg))
    return _renderer


def article_to_text(article: dict[str, Any]) -> str:
    """Render an article row into the embedding text exactly as the
    training pipeline did. Caller may pass camelCase parquet column
    names (`manufacturerName`, `categoryPaths`, …) or snake_case — the
    renderer normalises both via `column_rename` + `column_mapping`."""
    return _get_renderer().render_offer_text(article)


__all__ = ["article_to_text"]
