defaults:
  - model: base
  - data: default
  - trainer: default
  - optimizer: adamw
  - logger: mlflow
  - _self_

seed: 42
log_level: WARNING

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
