"""Bulk import the staged `offers_codes` parquets into Milvus.

Source: /data/datasets/offers_codes_staging.parquet/bucket=NN.parquet
Target collection: `offers_codes` (~158M rows, no dense vector).

Pipeline per source file:
  1. Read bucket=NN.parquet (id + text_codes only).
  2. Upload as-is to MinIO (no conversion needed — sparse_codes is generated
     server-side by the BM25 Function).
  3. Submit one `do_bulk_insert` per staged file and poll until Completed.

Schema (3 fields, plus the auto-generated sparse vector):

  id            VARCHAR(64)   PK                              (RAM)
  text_codes    VARCHAR(512)  whitespace-tokenised, lowercase, len 4-40
                              field-mmap                       (DISK)
  sparse_codes  SPARSE_FLOAT_VECTOR  generated by BM25(text_codes)
                                     SPARSE_INVERTED_INDEX, mmap.enabled=true
                                                              (DISK)

Memory invariant: only `id` + the inverted-index head live in RAM. text_codes
is mmap-backed; sparse posting lists are mmap-backed via the index param.

Index timing: SPARSE_INVERTED_INDEX is defined BEFORE the first bulk-insert
job. Milvus 2.6's bulk-insert pipeline auto-builds the index inline during
its IndexBuilding stage; post-hoc create_index would be a no-op. See
APRIL_21_offers_bulk_import.md for the prior incident.
"""

from __future__ import annotations

import argparse
import re
import shutil
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import boto3
from botocore.client import Config
from pymilvus import (
    Collection,
    CollectionSchema,
    DataType,
    FieldSchema,
    Function,
    FunctionType,
    connections,
    utility,
)

DEFAULT_DATA_DIR = Path("/data/datasets/offers_codes_staging.parquet")
COLLECTION = "offers_codes"
NUM_WORKERS = 8

S3_ENDPOINT = "http://localhost:9000"
S3_BUCKET = "a-bucket"
S3_PREFIX = "bulk_offers_codes"
S3_KEY = "minioadmin"
S3_SECRET = "minioadmin"

BUCKET_RE = re.compile(r"^bucket=\d{2}\.parquet$")


def s3_client():
    return boto3.client(
        "s3",
        endpoint_url=S3_ENDPOINT,
        aws_access_key_id=S3_KEY,
        aws_secret_access_key=S3_SECRET,
        config=Config(signature_version="s3v4"),
        region_name="us-east-1",
    )


def upload_one(src: Path) -> tuple[str, float, int]:
    s3 = s3_client()
    t0 = time.time()
    s3.upload_file(str(src), S3_BUCKET, f"{S3_PREFIX}/{src.name}")
    upload_t = time.time() - t0
    size = src.stat().st_size
    print(f"  {src.name}: upload={upload_t:5.1f}s size={size/1e9:.2f} GB", flush=True)
    return src.name, upload_t, size


def stage_and_submit(sources: list[Path], workers: int) -> dict[str, int]:
    print(f"Uploading + submitting {len(sources)} file(s) (workers={workers}) — pipelined",
          flush=True)
    jobs: dict[str, int] = {}
    t0 = time.time()
    with ProcessPoolExecutor(max_workers=workers) as ex:
        futs = {ex.submit(upload_one, s): s for s in sources}
        for fut in as_completed(futs):
            name, _, _ = fut.result()
            path = f"{S3_PREFIX}/{name}"
            job_id = utility.do_bulk_insert(collection_name=COLLECTION, files=[path])
            jobs[name] = job_id
            print(f"  [{int(time.time()-t0):4d}s] {name}: uploaded+submitted -> job {job_id}",
                  flush=True)
    print(f"All upload + submission done in {time.time() - t0:.1f}s", flush=True)
    return jobs


def build_collection(drop_existing: bool) -> Collection:
    if utility.has_collection(COLLECTION):
        if drop_existing:
            try:
                Collection(COLLECTION).release()
            except Exception:
                pass
            print(f"Dropping existing collection {COLLECTION!r}")
            utility.drop_collection(COLLECTION)
        else:
            print(f"Reusing existing collection {COLLECTION!r}")
            return Collection(COLLECTION)

    fields = [
        # PK stays in RAM (Milvus needs it for primary-key index).
        FieldSchema(
            name="id",
            dtype=DataType.VARCHAR,
            max_length=64,
            is_primary=True,
        ),
        # Field-data mmap on text_codes — only the BM25 *index* is in RAM.
        FieldSchema(
            name="text_codes",
            dtype=DataType.VARCHAR,
            max_length=512,
            mmap_enabled=True,
            enable_analyzer=True,
            analyzer_params={
                "tokenizer": "whitespace",
                "filter": [
                    "lowercase",
                    {"type": "length", "min": 4, "max": 40},
                ],
            },
        ),
        FieldSchema(name="sparse_codes", dtype=DataType.SPARSE_FLOAT_VECTOR),
    ]

    schema = CollectionSchema(
        fields,
        description="Offer code identifiers (EAN/MPN/article) for BM25 retrieval",
    )
    # BM25 over text_codes → sparse_codes, generated server-side.
    schema.add_function(Function(
        name="bm25_codes",
        function_type=FunctionType.BM25,
        input_field_names=["text_codes"],
        output_field_names=["sparse_codes"],
    ))

    col = Collection(COLLECTION, schema=schema)
    print(f"Created collection {COLLECTION!r} with {len(fields)} fields + BM25 function")
    for f in fields:
        mmap_flag = f.params.get("mmap_enabled", False)
        print(f"  - {f.name:<14} {f.dtype.name:<22}  mmap={mmap_flag}")
    return col


def wait_for_jobs(jobs: dict[str, int]) -> int:
    pending = dict(jobs)
    total_rows = 0
    t0 = time.time()
    while pending:
        next_pending = {}
        for name, job_id in pending.items():
            state = utility.get_bulk_insert_state(job_id)
            if state.state_name == "Completed":
                total_rows += state.row_count
                print(
                    f"  [{int(time.time()-t0):4d}s] {name}: Completed "
                    f"({state.row_count:,} rows)"
                )
            elif state.state_name == "Failed":
                raise RuntimeError(f"{name}: bulk insert FAILED -- {state.infos}")
            else:
                next_pending[name] = job_id
        if next_pending:
            still = ", ".join(
                f"{n}={utility.get_bulk_insert_state(j).progress}%"
                for n, j in next_pending.items()
            )
            print(f"  [{int(time.time()-t0):4d}s] pending: {still}", flush=True)
            time.sleep(10)
        pending = next_pending
    return total_rows


def wait_index_finished(col: Collection, field: str, poll_s: int = 5) -> float:
    """state=Finished with indexed_rows=0 on a non-empty collection means
    no build task is registered, NOT success. Only accept Finished when
    indexed_rows == total_rows. APRIL_21_offers_bulk_import.md."""
    t0 = time.time()
    while True:
        progress = utility.index_building_progress(col.name, index_name=field)
        total = progress.get("total_rows", 0)
        indexed = progress.get("indexed_rows", 0)
        pending = progress.get("pending_index_rows", 0)
        state = progress.get("state", "?")
        elapsed = time.time() - t0
        print(
            f"  [{field}] t={elapsed:6.1f}s  state={state}  "
            f"indexed={indexed:,}/{total:,}  pending={pending:,}",
            flush=True,
        )
        if state == "Finished" and (total == 0 or indexed == total):
            return elapsed
        time.sleep(poll_s)


def select_buckets(data_dir: Path, filter_name: str | None) -> list[Path]:
    files = [p for p in sorted(data_dir.iterdir()) if BUCKET_RE.match(p.name)]
    if not files:
        raise SystemExit(f"No bucket=NN.parquet files under {data_dir}")
    if filter_name:
        files = [p for p in files if p.name == filter_name]
        if not files:
            raise SystemExit(f"No bucket matching {filter_name!r} under {data_dir}")
    return files


def smoke_test(col: Collection) -> None:
    """Post-load sanity: each placeholder query should produce 0 hits, while
    a known popular EAN should produce many. We don't fail the script if a
    smoke test surprises — just print loudly so the operator notices."""
    cases = [
        ("00000000",       "expect 0 (all-zero placeholder)"),
        ("4031100000000",  "expect 0 (frequency-capped)"),
        ("9999999999999",  "expect 0 (all-nines placeholder)"),
        ("n/a",            "expect 0 (literal placeholder, sub-min length actually)"),
        ("magnet",         "expect 0 (pure-letter MPN dropped)"),
        ("rj45",           "expect many (real popular SKU)"),
    ]
    print("\nPost-load smoke tests:", flush=True)
    for q, note in cases:
        res = col.search(
            data=[q.lower()],
            anns_field="sparse_codes",
            param={"metric_type": "BM25"},
            limit=10,
            output_fields=["id"],
        )
        n = len(res[0]) if res else 0
        print(f"  {q!r:>20}  hits={n:>3}  ({note})")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    p.add_argument("--bucket", default="",
                   help="Single bucket filename (e.g., 'bucket=00.parquet'). Default: all.")
    p.add_argument("--host", default="localhost")
    p.add_argument("--port", default="19530")
    p.add_argument("--workers", type=int, default=NUM_WORKERS)
    p.add_argument("--no-drop", action="store_true",
                   help=f"Do not drop existing {COLLECTION!r} collection.")
    p.add_argument("--skip-load", action="store_true")
    p.add_argument("--skip-smoke", action="store_true")
    args = p.parse_args()

    sources = select_buckets(args.data_dir, args.bucket or None)
    print(f"Found {len(sources)} bucket(s) to import:")
    for s in sources:
        print(f"  - {s}")

    wall = time.time()
    connections.connect(alias="default", host=args.host, port=args.port)
    col = build_collection(drop_existing=not args.no_drop)

    print("\nDefining SPARSE_INVERTED_INDEX (mmap.enabled=true) on sparse_codes...",
          flush=True)
    col.create_index(
        field_name="sparse_codes",
        index_params={
            "index_type": "SPARSE_INVERTED_INDEX",
            "metric_type": "BM25",
            "params": {"mmap.enabled": "true"},
        },
        index_name="sparse_codes",
    )

    t0 = time.time()
    jobs = stage_and_submit(sources, args.workers)
    stage_submit_s = time.time() - t0

    print("\nWaiting for bulk-insert jobs to complete (includes IndexBuilding)...",
          flush=True)
    t0 = time.time()
    total_rows = wait_for_jobs(jobs)
    ingest_s = time.time() - t0

    print(f"\nFlushing... (upload+submit: {stage_submit_s:.1f}s, "
          f"ingest wait: {ingest_s:.1f}s, rows: {total_rows:,})", flush=True)
    t0 = time.time()
    col.flush()
    flush_s = time.time() - t0
    print(f"  flush: {flush_s:.1f}s  num_entities={col.num_entities:,}", flush=True)

    print("\nVerifying index build state...", flush=True)
    idx_s = wait_index_finished(col, "sparse_codes")
    progress = utility.index_building_progress(col.name, index_name="sparse_codes")
    assert progress["indexed_rows"] == total_rows, (
        f"sparse_codes indexed_rows={progress['indexed_rows']:,} != "
        f"total_rows={total_rows:,} — build was a no-op")
    print(f"  sparse_codes: indexed {progress['indexed_rows']:,}/"
          f"{progress['total_rows']:,} ✓", flush=True)

    load_s = 0.0
    if args.skip_load:
        print("\nSkipping col.load() as requested.")
    else:
        print("\nLoading collection...")
        t0 = time.time()
        col.load()
        load_s = time.time() - t0

    if not args.skip_load and not args.skip_smoke:
        smoke_test(col)

    total_wall = time.time() - wall
    print("\n=== summary ===")
    print(f"  rows:              {total_rows:,}")
    print(f"  upload+submit:     {stage_submit_s:7.1f}s  (pipelined)")
    print(f"  ingest wait:       {ingest_s:7.1f}s")
    print(f"  flush:             {flush_s:7.1f}s")
    print(f"  sparse index:      {idx_s:7.1f}s  (SPARSE_INVERTED_INDEX, mmap)")
    print(f"  load:              {load_s:7.1f}s")
    print(f"  total wall:        {total_wall:7.1f}s  ({total_wall/60:.1f} min)")
    print(f"  num_entities:      {col.num_entities:,}")


if __name__ == "__main__":
    main()
