[package]
name = "mongo-vendor-export"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }
futures-util = "0.3"
mongodb = "3"
num_cpus = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
uuid = "1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
